### ISSUE TITLE
ios build error in recent react-native 0.62.2

### ISSUE THREAD

**Issue by hyochan** [VirgilSecurity/virgil-e3kit-js#106]
**Describe the bug**
When running ios project, the build failed with below error that relates to [react-native-virgil-crypto](https://github.com/VirgilSecurity/react-native-virgil-crypto) in `react-native@0.62`. I am currently upgrading my `react-native` project in [PR](https://github.com/dooboolab/hackatalk-mobile/pull/126).

**To Reproduce**
1. git clone https://github.com/dooboolab/hackatalk-mobile.git
2. git checkout upgrade/react-native@0.62
3. cd ios && pod install && cd ..
4. yarn start
5. yarn ios (in another terminal)

**Expected behavior**
Build succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/27461460/79303206-48ccf600-7f29-11ea-82c2-206e91f2a4a9.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.3

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.4

**Additional context**
I can confirm that this is `react-native-virgil-crypto` issue since the build succeeded after uninstalling just `react-native-virgil-cryto` which also occurs a runtime error afterward since this is needed in e3kit.

**Comment by snanovskyi** [comment]
Hi @hyochan 👋

React Native 0.62 includes Flipper by default. The problem is that Flipper doesn't work with `use_frameworks!`. Maybe they will change it later or provide a workaround for it.

So I've created a new project with react-native cli and did the following changes to make it work on iOS:
- Disable Flipper in [Podfile](https://github.com/dooboolab/hackatalk-mobile/blob/upgrade/react-native%400.62/ios/Podfile#L89)
- Remove(or comment out) Flipper initialization in [AppDelegate.m](https://github.com/dooboolab/hackatalk-mobile/blob/upgrade/react-native%400.62/ios/HackaTalk/AppDelegate.m#L12)
- Install pods

I haven't tried it on Android yet because I don't have Android Studio on my machine right now.

I'll let you know when I will have a complete working example for both platforms.

**Comment by snanovskyi** [comment]
Update: it works without any changes on Android.

Let me know if you have any issues with the solution.

**Comment by snanovskyi** [comment]
Complete working example - https://github.com/VirgilSecurity/react-native-virgil-crypto/tree/master/examples/Example62

**Comment by hyochan** [comment]
> Hi @hyochan 👋
> 
> React Native 0.62 includes Flipper by default. The problem is that Flipper doesn't work with `use_frameworks!`. Maybe they will change it later or provide a workaround for it.
> 
> So I've created a new project with react-native cli and did the following changes to make it work on iOS:
> 
> * Disable Flipper in [Podfile](https://github.com/dooboolab/hackatalk-mobile/blob/upgrade/react-native%400.62/ios/Podfile#L89)
> * Remove(or comment out) Flipper initialization in [AppDelegate.m](https://github.com/dooboolab/hackatalk-mobile/blob/upgrade/react-native%400.62/ios/HackaTalk/AppDelegate.m#L12)
> * Install pods
> 
> I haven't tried it on Android yet because I don't have Android Studio on my machine right now.
> 
> I'll let you know when I will have a complete working example for both platforms.

@snanovskyi Wow. I really appreciate your response. Thanks.
However, I thought we don't need `use_frameworks` any more [related to StackOverflow](https://stackoverflow.com/questions/41210249/why-do-we-use-use-frameworks-in-cocoapods). Could `virgil` be updated instead of `react-native` itself?

**Comment by snanovskyi** [comment]
Thank you for that link!
As I mentioned in multiple issues across different repos, our React Native library uses https://github.com/VirgilSecurity/virgil-crypto-x under the hood for iOS and that library doesn't work without `use_frameworks!`.
I need some help from our iOS/Mac engineers to figure it out :)
@sanjoDeundiak @Ogerets

**Comment by hyochan** [comment]
Looking into it. I really don't want to miss flipper. I bet engineers in your team may figure it out 🥂. 
Here is [another link](https://stackoverflow.com/questions/33492873/using-cocoapods-without-use-frameworks-in-swift/49347198#49347198) 🙏

**Comment by hyochan** [comment]
Are there any updates for using `use_framework`? I'm still hesitating to upgrade our `RN` version for the current issue.

**Comment by SanjoDeundiak** [comment]
Hi @hyochan . Unfortunately we do not support dependencies on our native crypto libraries (that are used under the hood in react native case) without use_frameworks!. This is caused by many reasons (swift language, transitive dependencies, build specificities of our core C library, requirement for our iOS library to be available for both Carthage and CocoaPods users) and we are not able to change it in the nearest feature. Fortunately, @snanovskyi will guide you how to make your setup work using Carthage to link out libraries to your react native solution, this will allow you update your react version, use flipper and e3kit simultaneously.

**Comment by hyochan** [comment]
Thanks for the assistance and for sharing plans for supporting this. However, I think using two package managers in an app isn't a good solution. Using both cocoapod and carthage may lead to some other problems we've not met yet. Most of the S/W problems occur in integration. I am pretty unhappy with this decision. I hope we can find a better solution.

This is just my opinion.
