### ISSUE TITLE
Electron compatibility

### ISSUE THREAD

**Issue by maxogden** [VirgilSecurity/virgil-e3kit-js#30]
Hi, I'm trying to `import { EThree } from '@virgilsecurity/e3kit'` in an Electron 4.1.5 BrowserWindow w/ `babel-register@~6.22.0` and running into a number of issues. I was just wondering if there was a working Electron reference project I could check out.

First issue is when it tries to `import { EThree } from '@virgilsecurity/e3kit'` it gets to `dist/e3kit.browser.es.js` and fails with:

```
Uncaught SyntaxError: Unexpected token export
```

As a quick workaround I tried changing it to `require('@virgilsecurity/e3kit/dist/e3kit.browser.umd.min.js').` which results in:

```
virgil-crypto-pythia.browser.es.js:2999 [global-script] EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'".
```

**Comment by maxogden** [comment]
I'm trying to compile the `.ts` myself but also hitting errors:

```
virgil-e3kit-js $ tsc
node_modules/virgil-sdk/dist/types/Client/Connection.d.ts:6:57 - error TS2304: Cannot find name 'Response'.

6     get(endpoint: string, accessToken: string): Promise<Response>;
                                                          ~~~~~~~~

node_modules/virgil-sdk/dist/types/Client/Connection.d.ts:7:73 - error TS2304: Cannot find name 'Response'.

7     post(endpoint: string, accessToken: string, data?: object): Promise<Response>;
                                                                          ~~~~~~~~

node_modules/virgil-sdk/dist/types/Client/Connection.d.ts:27:57 - error TS2304: Cannot find name 'Response'.

27     get(endpoint: string, accessToken: string): Promise<Response>;
                                                           ~~~~~~~~

node_modules/virgil-sdk/dist/types/Client/Connection.d.ts:35:73 - error TS2304: Cannot find name 'Response'.

35     post(endpoint: string, accessToken: string, data?: object): Promise<Response>;
                                                                           ~~~~~~~~


Found 4 errors.

virgil-e3kit-js $ tsc -v
Version 3.4.5
```

**Comment by maxogden** [comment]
Ok I got the typescript compiled (had to add `dom` to typescript config), but when loaded it fails at loading `virgil-crypto`. 

```
ELECTRON_ASAR.js:160 Uncaught Error: The module '/home/max/exodus/exodus/src/node_modules/virgil-crypto/virgil_crypto_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
```

Ideally I'd like to load the native version of the module, but I also noticed that `virgil-crypto` doesn't seem to host precompiled binaries for Electron (https://github.com/VirgilSecurity/virgil-crypto-javascript/blob/master/scripts/download-node-addon.js#L16).

**Comment by xlwknx** [comment]
Hi @maxogden 
This package currently not tested with Electron and NodeJS, so we don't have example project yet. We will add NodeJS support it the next releases. For now you could try to compile sources by yourself. 
Problem with compilation is solving by running `npm rebuild`, because it seems to be compiled for another version of node. So precompiling should not be a problem.
[Virgil SDK](https://github.com/VirgilSecurity/virgil-sdk-javascript) and [Virgil Crypto](https://github.com/VirgilSecurity/virgil-crypto-javascript) already support Electron, so theoretically there should not be a problem to run E3kit on node. 
But if you find other problems please write it here, it will help add NodeJS support faster and help you in a first place.
