### ISSUE TITLE
EThree instance persists after sign-out/sign-in

### ISSUE THREAD

**Issue by paolospag** [VirgilSecurity/virgil-e3kit-js#41]
Hi,
I noticed a big limit when I sign-out with a certain account and sign-in with another account in the same device/navigation session, the `EThree` class instance persists even after the `cleanup` method:

```jsx
...
else {
  // If user signs out, we clean his private key on device
  eThreePromise.then(eThree => eThree.cleanup());
}
...
```

If I try to get instance of `EThree`, I see previous user id and not the current signed-in user id:
```jsx
....
this._eThree = await eThreePromise;
console.log(this._eThree); // <-- THIS RETURNS PREVIOUS USER
...
```

I believe that this does not overwrite existing instances:
```jsx
...
eThreePromise = EThree.initialize(getToken, {keyEntryStorage});
...
```
and it is not re-initialized when another user account sign-in the app, causing this error when I try to send chat messages:
![Schermata 2019-05-31 alle 17 39 15](https://user-images.githubusercontent.com/35046292/59411859-810d2080-8dbc-11e9-8a90-b4ca3221f661.png)

I don't use `e3kit`, but I try to reproduce `EThree` class using `virgil-crypto` and `virgil-sdk` and the problem should be present however.

**Comment by xlwknx** [comment]
Hi, @paolospag 
1. `EThree.cleanup` doesn't delete saved instances of the class. It deletes local private key on the device. 
2. `EThree.initialize` always returns a new promise which resolves with new instance.
3. 
```
this._eThree = await eThreePromise;
console.log(this._eThree); // <-- THIS RETURNS PREVIOUS USER
```
This works as expected. You resolve promise once by `await`. Then you save instance once. But you should rewrite `this.eThree` to make reference to a new instance. Make a new initialize call to get new promise for a new user.
```
this.eThree = await EThree.initialize(getToken, {keyEntryStorage});
```

**Comment by paolospag** [comment]
Hi @xlwknx 

1. I know `EThree.cleanup` deletes just the local private key, I mentioned it only because I previously thought it would also cancel all the istances
2. but seems not to work well (and now I'll explain why, see point 3)
3. this snippet code is found in a signed-in screen (like Profile screen) that re-renders every time user sign-out/sign-in:
```jsx
this._eThree = await eThreePromise;
console.log(this._eThree); // <-- THIS RETURNS PREVIOUS USER
```

I'm using your documentation code to observe user auth state:
```jsx
let eThreePromise = new Promise((resolve, reject) => {
    firebase.auth().onAuthStateChanged(user => {
        if (user) {
            const getToken = () => user.getIdToken().then(fetchToken);
            const keyEntryStorage = createNativeKeyEntryStorage();
            eThreePromise = EThree.initialize(getToken, {keyEntryStorage});
            eThreePromise.then(resolve).catch(reject);
        } else {
            // If user signs out, we clean his private key on device
            eThreePromise.then(eThree => eThree.cleanup());
        }
    });
});
```
If everything works as you say in point 3, when the user sign-out and sign-in with another account, this method should be instantiated again:
```jsx
eThreePromise = EThree.initialize(getToken, {keyEntryStorage});
```
but is not so: I have to restart the app to get EThree instance with new user id

**Comment by xlwknx** [comment]
@paolospag I'm try to explain again.
1. We have EThree class. `EThree.initialize` is a static method that returns `EThree` class `instance`.
In javascript it is impossible "cancel" instances outside of managed object. We don't store `eThree` instances at all. It is managed by application code. We just return instance. That's why cleanup doesn't delete outer instances. Instance get deleted by garbage collector, when there are no reference to that instance. 
2. So the EThree.initialize works as expected - return new instance on each `initialize` function call. 
3. When you do `this._eThree = await eThreePromise` you resolve Promise. Promise - is not a event. When you resolve is resolved, it returns `eThree instance` and it make a reference to `this._eThree`. If you will keep this reference without referencing new instance of eThree it will be same instance. As expected.
4. So you using this snippet wrong. When another user logs in, this snippet refresh `eThreePromise` variable by this string `eThreePromise = EThree.initialize(getToken, {keyEntryStorage});`. And in your code you assign `this._eThree = await eThreePromise;`. eThreePromise - resolved once and assigned once, so that's why you have same instance for different users. But in meantime, `eThreePromise` variable got changed with a new promise, which will resolved again with new instance. But it need to be properly assigned again to the object, where you keep this reference.

I'm closing this issue because it is not an e3kit problem.

**Comment by paolospag** [comment]
@xlwknx everything you're saying makes sense to me, but I don't know why it's not working as I expect.
I've created a separated file called`eThree.js` and I did what you suggested in the #24 issue

> And while looking on your code, I have a tip for you. You don't need to initialize e3kit in all component. You could just initialize it once in separate module. You can use initialize snippet from official guide and add export eThreePromise;. Then you can import that promise from different components, and this promise will be resolved with actual user eThree instance.

but when I sign-out and sign-in with other account, `EThree` instance persists with previous account, not the current. I think the problem is just the separated file.
Is not related to `e3kit`, I agree, but do you have suggestions on how to improve my code?

**Comment by xlwknx** [comment]
Try to assign eThree instance to common object property and re-assign it on another user is signing in. 
Maybe import/export system in react native works another way then in browser webpack. Try to assign eThree instance to `global.eThreePromise` variable or to the property of the common object. But be sure that you do proper reassigning of that property.

But I'm not sure exactly what is your problem without reproducible code.
