### ISSUE TITLE
Signature verification failed while decrypt

### ISSUE THREAD

**Issue by vkkan** [VirgilSecurity/virgil-e3kit-js#42]
We are integrated e3kit on our react native firebase chat module , everything works fine but when user has multiple cards[ Previous card entry] and send message other parties not able to decrypt using senders public key.

When I check the no of cards its 4 but I have only 3 users in that application , I am not able to delete the card using e3kit, I have tried installing CLI to do the same but no luck since in cli its asking for " access token " and given below error Module: virgil/sdk. Error code: 3. REST Query to Virgil Service failed. HTTP Code: 401; Virgil Code: 20302; Description: The Virgil access token validation has failed on the Virgil Authenticator service 

Let me how do we handle this

**Comment by xlwknx** [comment]
Hi @vkkan.

Okay, I got your problem. When `rotatePrivateKey` is used by user, he gets new card (Private and Public Key pair). And you trying to decrypt message encrypted with old user private key. So when you try to decrypt message decrypted with old private key and using his new public key you getting `signing verification error`. So this is expected behavior. 

`rotatePrivateKey` is used in cases when user lost his private key or it is got compromised. That's why `lookupPublicKey` always returns actual public key, and not previous. 

About Virgil Cli:
It seems you are using old CLI, but there a good news, we got a new version. It is pre-release only, but cards deletion is working there, here brief instruction (I'm using MacOS, so I'll use bash commands):
1. Download latest release of Virgil CLI for your platform (currently v5.0.2-alpha5):
https://github.com/VirgilSecurity/virgil-cli/releases
2. put `config.json`which you are using for `e3kit-firebase-function`
3. `cd path/to/virgil_5.0.2-alpha5_macOS_x86_64`
4. run `./virgil cards search -c ./config.json FIREBASE_UID_IDENTITY`
and copy card id.
5. run `./virgil cards delete CARD_ID`
and then past card identity

Please write here how it works for you.

**Comment by vkkan** [comment]
Super , will adjust my key creation accordingly and will let you know about the cli

**Comment by xlwknx** [comment]
@vkkan Hope everything went good.
