### ISSUE TITLE
Error on sign-in again after page refresh

### ISSUE THREAD

**Issue by psico-digital** [VirgilSecurity/virgil-e3kit-js#65]
This is my login code:
```
async login () {
  try {
   // FIREBASE AUTH
   await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.NONE)
   await firebase.auth().signInWithEmailAndPassword(email, password)

   // VIRGIL INITIALIZE
   const getToken = firebase.functions().httpsCallable('getVirgilJwt')
   const eThree = await EThree.initialize(() => getToken().then(result => result.data.token))
   const hasLocalPrivateKey = await eThree.hasLocalPrivateKey()
   if (!hasLocalPrivateKey) await eThree.restorePrivateKey(secret)

     ...
  } catch (error) {
     ...
  }
}
```
When the user first signs in, everything works correctly, but when he refreshes the page and tries to sign in again, this error occurs:

`CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0`

The cloud function `getVirgilJwt` does not trigger anymore. PS: Auth and data are reset when the user refreshes the page.

Any idea?

**Comment by snanovskyi** [comment]
Hi @psico-digital!

This error means that `.wasm` file is invalid. Maybe your local `.wasm` file got corrupted somehow. Try to remove `node_modules` and install packages again. It might help.

Otherwise we need more details on your environment (browser, E3kit version, etc.). Also a small demo that reproduces the problem would speed up this process a lot.
