### ISSUE TITLE
Support Expo managed workflow by allowing for alternative implementations of native modules

### ISSUE THREAD

**Issue by brentvatne** [VirgilSecurity/virgil-e3kit-js#95]
**Is your feature request related to a problem? Please describe.**
This project currently depends on modules that are not included in the Expo SDK, but their functionality can be provided by other APIs that are in the Expo SDK:

- [x] @react-native-community/async-storage: import from React Native instead, Expo still exports it from there.
- [x] @virgilsecurity/key-storage-rn: this doesn't seem to have any native code dependencies of its own
- [x] react-native-keychain: [SecureStore](https://docs.expo.io/versions/latest/sdk/securestore/) - already used here https://github.com/VirgilSecurity/virgil-key-storage-rn/blob/master/src/ExpoStorage.ts#L1 but import should change to `import * as SecureStore from 'expo-secure-store';`
- [?] react-native-virgil-crypto: unsure exactly what is needed here, maybe [Crypto](https://docs.expo.io/versions/latest/sdk/crypto/) from the Expo SDK would work too, it is similar to the Node crypto API.

**Describe the solution you'd like**
It'd be lovely if this worked out of the box for folks using the managed workflow. It's worth noting also that because you can use the Expo SDK packages in any React Native app it would also work in any app, and it'd continue working when you eject.

**Describe alternatives you've considered**
Ejecting to add custom code - but it would be great to avoid this given that it should all be doable with the APIs included in the SDK.

**Additional context**
I received a question from an Expo user about this and so I investigated on their behalf.

**Comment by hyochan** [comment]
Thank you @brentvatne for opening an issue! If `react-native-keychain` is an only native dependent library, it would be easy to make it compatible with `expo`.

**Comment by snanovskyi** [comment]
Hi guys 👋

First of all we like Expo and enjoy the DX and benefits it provides 👍

We also know about Expo APIs that can substitute some libraries(storage, keychain, etc.).
We even provide a way to use SecureStorage with previous version of our library as @brentvatne mentioned.

Unfortunately the problem is that our crypto library is much more than Node.js crypto API. That's why it's not easy to make it compatible. In our case we need to create a lot of complex stuff from our C library from scratch in JavaScript.

As a workaround we tried to configure Emscripten(tool that we use to compile C library) to create asm.js file for React Native but last time we had not luck to make it work. Also asm.js performance is unsatisfying on mobile devices.

That's why we created a separate native module for React Native.

**Comment by snanovskyi** [comment]
To sum up, you need to eject Expo project or create React Native project without it.

If you need help setting up your project you can jour our [Slack community](https://virgilsecurity.com/join-community) and get in touch with our team there.

**Comment by hyochan** [comment]
@brentvatne How do you think about an [issue](https://github.com/VirgilSecurity/virgil-e3kit-js/issues/97#issuecomment-590275612) here? Do you think this update should be in `expo` or in `virgil` sdk?
